name: Update daily wallpaper

on:
  schedule: # execute every 12 hours
    - cron: "* */12 * * *"

  # allows to manually run the job at any time
  workflow_dispatch:

jobs:
  update-readme:
    name: Update Image README
    runs-on: ubuntu-latest
    steps:
      - uses: siddharth2016/update-readme-image@main
        with:
          WIDTH: "100%"
          HEIGHT: "100%"
          ALIGN: center # duhhh
          IMG_ALT: Daily Wallpaper
          IMG_PATH: images
          IMG_REPOSITORY: DenverCoder1/minimalistic-wallpaper-collection
